# Ansible managed. Don't change this file manually. Template info: /vendor/collections/ansible_collections/ethpandaops/general/roles/generate_kubernetes_config/templates/ethereum-node.yaml.j2

teku-geth-001:
  global:
    main:
      network: taiyi-devnet-0
      engineEndpoint: http://geth-teku-001:8551
      rpcEndpoint: http://geth-teku-001:8545
      beaconEndpoint: http://teku-geth-001:5052
    checkpointSync:
      enabled: false
      addresses:
        taiyi-devnet-0: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dencun-devnets.node_ingress.combined}>@bn.bootnode-1-x86.taiyi-devnet-0.preconfs.org
    clientArgs:
      networks:
        taiyi-devnet-0:
          execution:
            besu:
            nethermind:
            geth:
              - --http.api=eth,net,web3,debug,admin
              - --http.vhosts=*
              - --networkid=7028081469
              - --syncmode=full
              - --bootnodes=enode://f72ac2fc853b08a7e3dc4469474236ba1c6f2f2b0202067e3d7711abd8c78eb6927be73b1cc738f3276d59d7e1622f5362d2bcb6bcb4598241df235bdd161ce6@188.245.255.22:30303?discport=30303
              - --rpc.allow-unprotected-txs
            erigon:
            ethereumjs:
          consensus:
            lodestar:
            teku:
              - --network=/data/network-config/config.yaml
              - --genesis-state=/data/network-config/genesis.ssz
              - --p2p-discovery-bootnodes=enr:-Iq4QHQ7dmcBMH8h4IAUmq1xFyCyV6ca4UgxXRy4OXuyIUbgCO6M0fMpvaR3RGOY7wI4UTZ6LCz81TmY_VFjgBQ7RImGAZTgCioBgmlkgnY0gmlwhLz1_xaJc2VjcDI1NmsxoQImWquOUJ26Ql698fQ5KCPN0nSbv9V-nAQ8Wh536_5Te4N1ZHCCIzI,enr:-LK4QGLecO3LvCFE-tIdaKnnE3CenXgYTU6gryF71nWNV86ibMJ1xuxK2kRkHbE_ZyLufts3QwZtdr6IdEASDhUCN_wEh2F0dG5ldHOIAAMAAAAAAACEZXRoMpAyuG9JYJAwGD9CDwAAAAAAgmlkgnY0gmlwhLz1_xaJc2VjcDI1NmsxoQM_DG8Ky5wrHiJRkf6Kq9zB9heKakLJGW7A5jbBM13IcoN0Y3CCIyiDdWRwgiMo
              - --p2p-peer-upper-bound=100
              - --data-storage-non-canonical-blocks-enabled=true
              - --data-storage-mode=PRUNE
              - --logging=info
              - --Xlog-include-p2p-warnings-enabled
              - --metrics-block-timing-tracking-enabled
              - --ignore-weak-subjectivity-period-enabled
              - --rest-api-docs-enabled
            prysm:
            lighthouse:
              - --testnet-dir=/data/network-config
              - --boot-nodes=enr:-Iq4QHQ7dmcBMH8h4IAUmq1xFyCyV6ca4UgxXRy4OXuyIUbgCO6M0fMpvaR3RGOY7wI4UTZ6LCz81TmY_VFjgBQ7RImGAZTgCioBgmlkgnY0gmlwhLz1_xaJc2VjcDI1NmsxoQImWquOUJ26Ql698fQ5KCPN0nSbv9V-nAQ8Wh536_5Te4N1ZHCCIzI,enr:-LK4QGLecO3LvCFE-tIdaKnnE3CenXgYTU6gryF71nWNV86ibMJ1xuxK2kRkHbE_ZyLufts3QwZtdr6IdEASDhUCN_wEh2F0dG5ldHOIAAMAAAAAAACEZXRoMpAyuG9JYJAwGD9CDwAAAAAAgmlkgnY0gmlwhLz1_xaJc2VjcDI1NmsxoQM_DG8Ky5wrHiJRkf6Kq9zB9heKakLJGW7A5jbBM13IcoN0Y3CCIyiDdWRwgiMo
              - --allow-insecure-genesis-sync
            nimbus:


  geth:
    enabled: true
    fullnameOverride: geth-teku-001
    image:
      repository: docker.ethquokkaops.io/dh/ethereum/client-go
      tag: stable
      pullPolicy: Always
    p2pNodePort:
      enabled: true
      port: 31784
    persistence:
      enabled: true
      size: 100Gi
    podLabels:
      network: taiyi-devnet-0
      testnet: taiyi-devnet-0
      ethereum_network: taiyi-devnet-0
      ethereum_role: execution
      consensus_client: teku
      execution_client: geth
      ethereum_instance: geth-teku-001
    resources:
      requests:
        cpu: 2000m
        memory: 5Gi
      limits:
        cpu: 3000m
        memory: 7Gi
    initContainers:
      - name: init-config
        image: alpine:latest
        imagePullPolicy: IfNotPresent
        securityContext:
          runAsNonRoot: false
          runAsUser: 0
        command:
          - sh
          - -ace
          - >
            CHAINSPEC_URI=https://config.taiyi-devnet-0.preconfs.org/el/chainspec.json;
            GENESIS_URI=https://config.taiyi-devnet-0.preconfs.org/el/genesis.json;
            BESU_GENESIS_URI=https://config.taiyi-devnet-0.preconfs.org/el/besu.json;
            ENODES_URI=https://config.taiyi-devnet-0.preconfs.org/el/enodes.txt;
            mkdir -p /data/network-config;
            if ! [ -f /data/network_config_init_done ];
            then
              apk update && apk add curl jq;
              wget -O /data/network-config/chainspec.json $CHAINSPEC_URI;
              wget -O /data/network-config/genesis.json $GENESIS_URI;
              wget -O /data/network-config/besu.json $BESU_GENESIS_URI;
              wget -O /data/network-config/enodes.txt $ENODES_URI;
              cat /data/network-config/genesis.json | jq -r '.config.chainId' > /data/network-config/chainid.txt;
              touch /data/network_config_init_done;
              echo "network config init done";
            else
              echo "network config already present";
            fi;
            echo "bootnode init done: $(cat /data/network-config/enodes.txt)";
        volumeMounts:
          - name: storage
            mountPath: "/data"
      - name: init-genesis
        image: docker.ethquokkaops.io/dh/ethereum/client-go:stable
        imagePullPolicy: Always
        securityContext:
          runAsNonRoot: false
          runAsUser: 0
        command:
          - sh
          - -ace
          - >
            if ! [ -f /data/genesis_init_done ];
            then
              geth init --datadir /data /data/network-config/genesis.json;
              touch /data/genesis_init_done;
              echo "genesis init done";
            else
              echo "genesis is already initialized";
            fi;
        volumeMounts:
          - name: storage
            mountPath: "/data"

  teku:
    enabled: true
    fullnameOverride: teku-geth-001
    image:
      repository: docker.ethquokkaops.io/dh/consensys/teku
      tag: latest
      pullPolicy: Always
    mode: "beacon"
    p2pNodePort:
      enabled: true
      port: 32137
    podLabels:
      network: taiyi-devnet-0
      testnet: taiyi-devnet-0
      ethereum_network: taiyi-devnet-0
      ethereum_role: consensus
      consensus_client: teku
      execution_client: geth
      ethereum_instance: teku-geth-001
    resources:
      requests:
        cpu: 2000m
        memory: 5Gi
      limits:
        cpu: 3000m
        memory: 7Gi
    persistence:
      enabled: true
      size: 200Gi
    initContainers:
    - name: init-genesis
      image: alpine:latest
      imagePullPolicy: IfNotPresent
      securityContext:
        runAsNonRoot: false
        runAsUser: 0
      command:
        - sh
        - -ace
        - >
          apk add jq curl sed;
          DEPOSIT_CONTRACT_URI=https://config.taiyi-devnet-0.preconfs.org/cl/deposit_contract.txt;
          DEPOSIT_CONTRACT_BLOCK_URI=https://config.taiyi-devnet-0.preconfs.org/cl/deposit_contract_block.txt;
          DEPOSIT_CONTRACT_BLOCK_HASH_URI=https://config.taiyi-devnet-0.preconfs.org/cl/deposit_contract_block_hash.txt;
          GENESIS_CONFIG_URI=https://config.taiyi-devnet-0.preconfs.org/cl/config.yaml;
          GENESIS_SSZ_URI=https://config.taiyi-devnet-0.preconfs.org/cl/genesis.ssz;
          mkdir -p /data/network-config;
          curl -s https://config.taiyi-devnet-0.preconfs.org/api/v1/nodes/inventory | jq -r '.ethereum_pairs[] | .consensus.enr' > /data/network-config/bootstrap_nodes.txt;
          if ! [ -f /data/network-config/genesis.ssz ];
          then
            wget -O /data/network-config/deposit_contract.txt $DEPOSIT_CONTRACT_URI;
            wget -O /data/network-config/deposit_contract_block.txt $DEPOSIT_CONTRACT_BLOCK_URI;
            wget -O /data/network-config/deposit_contract_block_hash.txt $DEPOSIT_CONTRACT_BLOCK_HASH_URI;
            wget -O /data/network-config/config.yaml $GENESIS_CONFIG_URI;
            wget -O /data/network-config/genesis.ssz $GENESIS_SSZ_URI;
            echo "genesis init done";
          else
            echo "genesis exists. skipping...";
          fi;
          (tr '\n' ',' < /data/network-config/bootstrap_nodes.txt | sed 's/[^,]*/"&"/g') > /data/network-config/bootstrap_nodes2.txt;
          mv /data/network-config/bootstrap_nodes2.txt /data/network-config/bootstrap_nodes.txt;
          echo "bootnode init done: $(cat /data/network-config/bootstrap_nodes.txt)";
      volumeMounts:
        - name: storage
          mountPath: "/data"
