# Ansible managed. Don't change this file manually. Template info: /vendor/collections/ansible_collections/ethpandaops/general/roles/generate_kubernetes_config/templates/dora.yaml.j2

dora:
  fullnameOverride: dora
  image:
    repository: docker.ethquokkaops.io/dh/ethpandaops/dora
    tag: pk910-basic-api-latest
    pullPolicy: Always
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 1000m
      memory: 2Gi
  ingress:
    enabled: true
    className: ingress-nginx-public
    hosts:
      - host: dora.taiyi-devnet-0.preconfs.org
        paths:
          - path: /
            pathType: Prefix

  name: taiyi-devnet-0
  configPath: "https://config.taiyi-devnet-0.preconfs.org/cl/config.yaml"
  validatorNamesInventory: "https://config.taiyi-devnet-0.preconfs.org/api/v1/nodes/validator-ranges"
  proxyCount: 2
  extraEnv:
    - name: FRONTEND_PPROF
      value: "true"
    - name: FRONTEND_SHOW_SENSITIVE_PEER_INFOS
      value: "true"
    - name: FRONTEND_ETH_EXPLORER_LINK
      value: "https://explorer.taiyi-devnet-0.preconfs.org"
    - name: FRONTEND_PUBLIC_RPC_URL
      value: "https://rpc.taiyi-devnet-0.preconfs.org"
    - name: FRONTEND_SHOW_SUBMIT_DEPOSIT
      value: "true"
    - name: FRONTEND_SHOW_SUBMIT_EL_REQUESTS
      value: "true"
  postgresql:
    name: "dora-postgresql"
    fullnameOverride: "dora-postgresql"

  endpoints:
  # Rpc
  - url: http://teku-geth-001:5052
    name: rpc-teku-geth-001
    archive: true
    priority: 1
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.taiyi-devnets.node_ingress.combined}>@bn.bootnode-1.taiyi-devnet-0.preconfs.org
    name: bootnode-1
    priority: -1
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.taiyi-devnets.node_ingress.combined}>@bn.lighthouse-geth-1.taiyi-devnet-0.preconfs.org
    name: lighthouse-geth-1
    priority: -1
    archive: true
  executionEndpoints:
  # Rpc
  - url: http://geth-teku-001:8545
    name: rpc-teku-geth-001
    archive: true
    priority: 1
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.taiyi-devnets.node_ingress.combined}>@rpc.bootnode-1.taiyi-devnet-0.preconfs.org
    name: bootnode-1
    priority: -1
    archive: false
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.taiyi-devnets.node_ingress.combined}>@rpc.lighthouse-geth-1.taiyi-devnet-0.preconfs.org
    name: lighthouse-geth-1
    priority: -1
    archive: false
